"use client";

import { motion, AnimatePresence } from "framer-motion";
import {
    X,
    Globe,
    Users,
    HelpCircle,
    MapPin,
    Timer,
    Trophy,
    Target,
    Wifi,
    Crown,
    Brain,
    Flame,
    ChevronRight,
} from "lucide-react";

interface HowToPlayModalProps {
    open: boolean;
    onClose: () => void;
}

const MODES = [
    {
        icon: Globe,
        title: "Classic Mode",
        color: "text-primary",
        bg: "bg-primary/15",
        steps: [
            { icon: MapPin, text: "You're dropped into a random Google Street View location anywhere in the world." },
            { icon: Target, text: "Look around using your mouse or touch to find clues -- signs, landmarks, road markings, vegetation." },
            { icon: MapPin, text: "Place your pin on the mini-map where you think you are." },
            { icon: Timer, text: "You have a time limit per round (default 60s). Guess before time runs out!" },
            { icon: Trophy, text: "Score up to 5,000 points per round. The closer your guess, the higher the score." },
        ],
    },
    {
        icon: Flame,
        title: "Campaign Mode",
        color: "text-orange-400",
        bg: "bg-orange-400/15",
        steps: [
            { icon: Globe, text: "Choose a country to explore from the world map." },
            { icon: MapPin, text: "Play 5 rounds exclusively within that country's borders." },
            { icon: Trophy, text: "Earn stars based on your total score (up to 3 stars per country)." },
            { icon: Target, text: "Complete all countries to master the globe!" },
        ],
    },
    {
        icon: Users,
        title: "LAN Multiplayer",
        color: "text-cyan-400",
        bg: "bg-cyan-400/15",
        steps: [
            { icon: Crown, text: "One player hosts a game and shares the party code (e.g. TRP-K7ZM)." },
            { icon: Wifi, text: "Up to 8 friends join using the code -- no account needed." },
            { icon: MapPin, text: "Everyone gets the same location and races to pin it on the map." },
            { icon: Trophy, text: "Points are awarded based on accuracy and displayed on a live leaderboard." },
        ],
    },
    {
        icon: HelpCircle,
        title: "Quiz Mode",
        color: "text-emerald-400",
        bg: "bg-emerald-400/15",
        steps: [
            { icon: Brain, text: "Choose a geography category (capitals, flags, landmarks, etc.)." },
            { icon: HelpCircle, text: "Answer 5 multiple-choice questions generated by AI." },
            { icon: Timer, text: "Each question has a 15-second timer -- think fast!" },
            { icon: Trophy, text: "Earn XP and TerraCredits based on your accuracy." },
        ],
    },
];

const TIPS = [
    "Look for text on signs -- even partial words can reveal the language and country.",
    "Sun position and shadows can hint at hemisphere and latitude.",
    "Road markings, driving side, and car types vary by region.",
    "Google coverage quality differs -- blurry images are often in Africa or South America.",
    "Antenna styles, power line shapes, and bollard colors are surprisingly region-specific.",
];

export function HowToPlayModal({ open, onClose }: HowToPlayModalProps) {
    return (
        <AnimatePresence>
            {open && (
                <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 0.2 }}
                    className="fixed inset-0 z-50 flex items-center justify-center p-4"
                    onClick={onClose}
                >
                    {/* Backdrop */}
                    <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" />

                    {/* Modal */}
                    <motion.div
                        initial={{ opacity: 0, scale: 0.95, y: 20 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.95, y: 20 }}
                        transition={{ duration: 0.25, ease: [0.25, 0.46, 0.45, 0.94] }}
                        onClick={(e) => e.stopPropagation()}
                        className="relative z-10 w-full max-w-2xl max-h-[85vh] overflow-y-auto rounded-2xl border border-white/10 bg-[oklch(0.12_0.02_260)] p-6 shadow-[0_20px_60px_rgba(0,0,0,0.7)] sm:p-8"
                    >
                        {/* Close button */}
                        <button
                            onClick={onClose}
                            className="absolute top-4 right-4 flex h-8 w-8 items-center justify-center rounded-lg border border-white/10 bg-white/[0.05] text-white/50 transition-colors hover:bg-white/[0.1] hover:text-white"
                        >
                            <X size={16} />
                        </button>

                        {/* Header */}
                        <div className="mb-6 text-center">
                            <h2 className="text-3xl font-extrabold uppercase italic tracking-wide text-white">
                                How to Play
                            </h2>
                            <div className="mx-auto mt-2 h-[3px] w-[100px] rounded-sm bg-primary shadow-[0_0_12px_oklch(0.65_0.2_265_/_0.55)]" />
                            <p className="mt-3 text-sm text-white/50">
                                TerraPin is a geography guessing game. Explore the world and test your knowledge!
                            </p>
                        </div>

                        {/* Game Modes */}
                        <div className="space-y-5">
                            {MODES.map((mode) => {
                                const ModeIcon = mode.icon;
                                return (
                                    <div
                                        key={mode.title}
                                        className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-4"
                                    >
                                        {/* Mode header */}
                                        <div className="mb-3 flex items-center gap-3">
                                            <div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${mode.bg}`}>
                                                <ModeIcon size={18} className={mode.color} />
                                            </div>
                                            <h3 className="text-base font-extrabold uppercase tracking-wide text-white">
                                                {mode.title}
                                            </h3>
                                        </div>

                                        {/* Steps */}
                                        <div className="space-y-2 pl-1">
                                            {mode.steps.map((step, i) => {
                                                const StepIcon = step.icon;
                                                return (
                                                    <div key={i} className="flex items-start gap-2.5">
                                                        <ChevronRight size={12} className="mt-0.5 shrink-0 text-white/20" />
                                                        <p className="text-[0.8rem] leading-relaxed text-white/60">
                                                            {step.text}
                                                        </p>
                                                    </div>
                                                );
                                            })}
                                        </div>
                                    </div>
                                );
                            })}
                        </div>

                        {/* Pro Tips */}
                        <div className="mt-6 rounded-xl border border-primary/10 bg-primary/[0.04] p-4">
                            <h3 className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-primary">
                                <Target size={13} />
                                Pro Tips
                            </h3>
                            <div className="space-y-2">
                                {TIPS.map((tip, i) => (
                                    <div key={i} className="flex items-start gap-2.5">
                                        <span className="mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded-full bg-primary/20 text-[0.55rem] font-bold text-primary">
                                            {i + 1}
                                        </span>
                                        <p className="text-[0.78rem] leading-relaxed text-white/55">
                                            {tip}
                                        </p>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Scoring */}
                        <div className="mt-5 rounded-xl border border-white/[0.06] bg-white/[0.02] p-4">
                            <h3 className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-white/50">
                                <Trophy size={13} className="text-yellow-400" />
                                Scoring
                            </h3>
                            <p className="text-[0.8rem] leading-relaxed text-white/50">
                                Each round awards up to <span className="font-bold text-white/80">5,000 points</span> based
                                on the distance between your guess and the actual location. A perfect guess earns full
                                points. At 2,000 km away you'll get about 1,839 points, and beyond 10,000 km you'll score
                                close to zero. Accuracy is everything!
                            </p>
                        </div>

                        {/* Close */}
                        <button
                            onClick={onClose}
                            className="shimmer mt-6 w-full rounded-xl bg-gradient-to-r from-primary to-primary/80 py-3 text-sm font-extrabold uppercase tracking-wide text-white transition-all duration-200 hover:shadow-[0_0_24px_oklch(0.65_0.2_265_/_0.45)]"
                        >
                            Got it!
                        </button>
                    </motion.div>
                </motion.div>
            )}
        </AnimatePresence>
    );
}
