/**
 * Multiplayer Zustand Store
 * Manages all state for the LAN multiplayer mode.
 * Subscribes to Supabase Realtime channel events and drives the UI.
 */

import { create } from "zustand";
import type { RealtimeChannel } from "@supabase/supabase-js";
import type { Position } from "@/types/game";
import type {
    MultiplayerPhase,
    LobbySettings,
    LobbyPlayer,
    LeaderboardEntry,
    RoundStartPayload,
    RoundResultsPayload,
    MatchOverPayload,
    GameStartingPayload,
    PlayerGuessedPayload,
    TimerUpdatePayload,
} from "@/types/multiplayer";
import { AVATAR_COLORS } from "@/types/multiplayer";
import {
    generatePartyCode,
    getPlayerId,
    createChannel,
    destroyChannel,
    trackPresence,
    presenceToPlayers,
    broadcastEvent,
    computeRoundResults,
    computeFinalLeaderboard,
} from "@/lib/multiplayer";
import type { PresencePayload } from "@/lib/multiplayer";
import { loadGoogleMaps } from "@/lib/google-maps";
import { findRandomStreetViewLocation } from "@/lib/geo";

/* ── Store Interface ──────────────────────────────────────── */

interface MultiplayerState {
    // Identity
    myId: string;
    myName: string;

    // Lobby
    phase: MultiplayerPhase;
    lobbyCode: string;
    players: LobbyPlayer[];
    settings: LobbySettings;
    isHost: boolean;

    // Gameplay
    currentRound: number;
    totalRounds: number;
    roundTimeLeft: number;
    actualPosition: Position | null;
    panoId: string | null;
    panoPosition: Position | null;
    guessPosition: Position | null;
    hasGuessed: boolean;
    isLoadingLocation: boolean;

    // Countdown
    countdownValue: number;

    // Results
    roundResults: RoundResultsPayload | null;
    leaderboard: LeaderboardEntry[];

    // Error
    error: string | null;

    // Actions
    setMyName: (name: string) => void;
    createLobby: () => void;
    joinLobby: (code: string) => void;
    leaveLobby: () => void;
    updateSettings: (settings: Partial<LobbySettings>) => void;
    startGame: () => void;
    setGuessPosition: (pos: Position) => void;
    submitGuess: () => void;
    returnToLobby: () => void;
    resetMultiplayer: () => void;
}

/* ── Internal refs (not in Zustand to avoid serialization) ── */

let channelRef: RealtimeChannel | null = null;
let timerInterval: ReturnType<typeof setInterval> | null = null;
let countdownInterval: ReturnType<typeof setInterval> | null = null;
let autoAdvanceTimeout: ReturnType<typeof setTimeout> | null = null;
let connectionTimeout: ReturnType<typeof setTimeout> | null = null;

/** Locations pre-generated by host for all rounds */
let roundLocations: { position: Position; panoId: string | null }[] = [];

/** Guesses received during current round (host only) */
let currentRoundGuesses: Map<string, { position: Position; timeSpent: number }> = new Map();

let roundStartTime = 0;

/** Guard to prevent hostEndRound from being called twice (timer + all-guessed race) */
let roundEnding = false;

/** Guard to prevent subscribe "SUBSCRIBED" callback from firing on reconnect */
let subscribedOnce = false;

function clearTimers() {
    if (timerInterval) { clearInterval(timerInterval); timerInterval = null; }
    if (countdownInterval) { clearInterval(countdownInterval); countdownInterval = null; }
    if (autoAdvanceTimeout) { clearTimeout(autoAdvanceTimeout); autoAdvanceTimeout = null; }
    if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
}

/* ── Default Settings ─────────────────────────────────────── */

const DEFAULT_SETTINGS: LobbySettings = {
    rounds: 5,
    timePerRound: 60,
    mapType: "world",
};

/** Connection timeout duration in ms */
const CONNECTION_TIMEOUT_MS = 15_000;

/* ── Store ────────────────────────────────────────────────── */

export const useMultiplayerStore = create<MultiplayerState>()((set, get) => ({
    myId: "",
    myName: "",
    phase: "menu",
    lobbyCode: "",
    players: [],
    settings: { ...DEFAULT_SETTINGS },
    isHost: false,
    currentRound: 0,
    totalRounds: 5,
    roundTimeLeft: 60,
    actualPosition: null,
    panoId: null,
    panoPosition: null,
    guessPosition: null,
    hasGuessed: false,
    isLoadingLocation: false,
    countdownValue: 3,
    roundResults: null,
    leaderboard: [],
    error: null,

    setMyName: (name) => set({ myName: name }),

    /* ── Create Lobby ─────────────────────────────────────── */
    createLobby: () => {
        const myId = getPlayerId();
        const { myName } = get();
        const code = generatePartyCode();
        const avatarColor = AVATAR_COLORS[0];

        set({
            phase: "creating",
            myId,
            lobbyCode: code,
            isHost: true,
            error: null,
        });

        try {
            const channel = createChannel(code);
            channelRef = channel;
            subscribedOnce = false;

            // Set up presence + broadcast listeners
            setupPresenceListeners(channel, get, set);
            setupBroadcastListeners(channel);

            // Connection timeout — if we don't connect in 15s, abort
            connectionTimeout = setTimeout(() => {
                const currentPhase = get().phase;
                if (currentPhase === "creating") {
                    console.error("[Multiplayer] Connection timeout while creating lobby");
                    destroyChannel();
                    channelRef = null;
                    set({ phase: "menu", error: "Connection timed out. Please try again." });
                }
            }, CONNECTION_TIMEOUT_MS);

            // Subscribe and track presence
            channel.subscribe(async (status) => {
                console.log("[Multiplayer] Channel subscribe status:", status);
                if (status === "SUBSCRIBED") {
                    // Guard: only transition phase on first subscribe (not reconnects)
                    if (subscribedOnce) {
                        // Re-track presence on reconnect to restore our presence
                        await trackPresence(channel, {
                            id: myId,
                            name: myName || "Host",
                            avatarColor,
                            isHost: get().isHost,
                        });
                        return;
                    }
                    subscribedOnce = true;

                    if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }

                    const result = await trackPresence(channel, {
                        id: myId,
                        name: myName || "Host",
                        avatarColor,
                        isHost: true,
                    });

                    if (result === "error" || result === "timed out") {
                        console.error("[Multiplayer] Failed to track presence:", result);
                        set({ phase: "menu", error: "Failed to join channel. Please try again." });
                        return;
                    }

                    set({ phase: "lobby" });
                } else if (status === "CHANNEL_ERROR") {
                    console.error("[Multiplayer] Channel error during lobby creation");
                    if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
                    set({ phase: "menu", error: "Failed to create lobby. Check your connection." });
                } else if (status === "TIMED_OUT") {
                    console.error("[Multiplayer] Channel subscription timed out");
                    if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
                    set({ phase: "menu", error: "Connection timed out. Check your internet connection." });
                } else if (status === "CLOSED") {
                    console.warn("[Multiplayer] Channel closed");
                    // Only reset if we're still in a creating/lobby phase (not mid-game)
                    const currentPhase = get().phase;
                    if (currentPhase === "creating" || currentPhase === "lobby") {
                        if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
                        set({ phase: "menu", error: "Connection closed. Please try again." });
                    }
                }
            });
        } catch (err) {
            console.error("[Multiplayer] Error creating lobby:", err);
            if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
            set({ phase: "menu", error: "Failed to create lobby. Check your Supabase configuration." });
        }
    },

    /* ── Join Lobby ───────────────────────────────────────── */
    joinLobby: (code) => {
        const myId = getPlayerId();
        const { myName } = get();
        const avatarIndex = Math.floor(Math.random() * AVATAR_COLORS.length);
        const avatarColor = AVATAR_COLORS[avatarIndex];
        const normalizedCode = code.toUpperCase();

        set({
            phase: "joining",
            myId,
            lobbyCode: normalizedCode,
            isHost: false,
            error: null,
        });

        try {
            const channel = createChannel(normalizedCode);
            channelRef = channel;
            subscribedOnce = false;

            setupPresenceListeners(channel, get, set);
            setupBroadcastListeners(channel);

            // Connection timeout — if we don't connect in 15s, abort
            connectionTimeout = setTimeout(() => {
                const currentPhase = get().phase;
                if (currentPhase === "joining") {
                    console.error("[Multiplayer] Connection timeout while joining lobby");
                    destroyChannel();
                    channelRef = null;
                    set({ phase: "menu", error: "Connection timed out. Check the party code and try again." });
                }
            }, CONNECTION_TIMEOUT_MS);

            channel.subscribe(async (status) => {
                console.log("[Multiplayer] Join channel status:", status);
                if (status === "SUBSCRIBED") {
                    // Guard: only transition phase on first subscribe
                    if (subscribedOnce) {
                        await trackPresence(channel, {
                            id: myId,
                            name: myName || "Player",
                            avatarColor,
                            isHost: get().isHost,
                        });
                        return;
                    }
                    subscribedOnce = true;

                    if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }

                    const result = await trackPresence(channel, {
                        id: myId,
                        name: myName || "Player",
                        avatarColor,
                        isHost: false,
                    });

                    if (result === "error" || result === "timed out") {
                        console.error("[Multiplayer] Failed to track presence:", result);
                        set({ phase: "menu", error: "Failed to join lobby. Please try again." });
                        return;
                    }

                    set({ phase: "lobby" });
                } else if (status === "CHANNEL_ERROR") {
                    console.error("[Multiplayer] Channel error during join");
                    if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
                    set({ phase: "menu", error: "Failed to join lobby. Check the party code." });
                } else if (status === "TIMED_OUT") {
                    console.error("[Multiplayer] Join channel timed out");
                    if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
                    set({ phase: "menu", error: "Connection timed out. Check your internet connection." });
                } else if (status === "CLOSED") {
                    console.warn("[Multiplayer] Join channel closed");
                    const currentPhase = get().phase;
                    if (currentPhase === "joining" || currentPhase === "lobby") {
                        if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
                        set({ phase: "menu", error: "Connection closed. Please try again." });
                    }
                }
            });
        } catch (err) {
            console.error("[Multiplayer] Error joining lobby:", err);
            if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
            set({ phase: "menu", error: "Failed to join lobby. Check the party code and your connection." });
        }
    },

    /* ── Leave Lobby ──────────────────────────────────────── */
    leaveLobby: () => {
        clearTimers();
        destroyChannel();
        channelRef = null;
        subscribedOnce = false;
        roundLocations = [];
        currentRoundGuesses.clear();
        set({
            phase: "menu",
            lobbyCode: "",
            players: [],
            isHost: false,
            currentRound: 0,
            roundResults: null,
            leaderboard: [],
            guessPosition: null,
            hasGuessed: false,
            actualPosition: null,
            panoId: null,
            panoPosition: null,
            error: null,
        });
    },

    /* ── Update Settings (Host only) ──────────────────────── */
    updateSettings: (partial) => {
        const newSettings = { ...get().settings, ...partial };
        set({ settings: newSettings });

        // Broadcast settings update to all players
        if (channelRef && get().isHost) {
            broadcastEvent(channelRef, "SETTINGS_UPDATE", newSettings);
        }
    },

    /* ── Start Game (Host only) ───────────────────────────── */
    startGame: async () => {
        const { isHost, settings, players } = get();
        if (!isHost || !channelRef) return;
        if (players.length < 2) {
            set({ error: "Need at least 2 players to start." });
            return;
        }

        set({ error: null, totalRounds: settings.rounds, isLoadingLocation: true });

        // Pre-generate all round locations FIRST, then broadcast + countdown
        try {
            await loadGoogleMaps();
            roundLocations = [];
            for (let i = 0; i < settings.rounds; i++) {
                const loc = await findRandomStreetViewLocation("world", 15);
                roundLocations.push({
                    position: { lat: loc.lat, lng: loc.lng },
                    panoId: "panoId" in loc ? (loc.panoId as string) ?? null : null,
                });
            }

            set({ isLoadingLocation: false });

            // Locations ready — broadcast GAME_STARTING so all clients start countdown together
            broadcastEvent(channelRef!, "GAME_STARTING", {
                totalRounds: settings.rounds,
                settings,
            } as GameStartingPayload);

            // Countdown is started from the GAME_STARTING broadcast listener
            // (host receives it too since self: true)
        } catch {
            set({ error: "Failed to generate locations. Please try again.", isLoadingLocation: false });
        }
    },

    /* ── Guess ────────────────────────────────────────────── */
    setGuessPosition: (pos) => {
        if (!get().hasGuessed) {
            set({ guessPosition: pos });
        }
    },

    submitGuess: () => {
        const { guessPosition, hasGuessed, myId, settings, roundTimeLeft } = get();
        if (!guessPosition || hasGuessed || !channelRef) return;
        // Prevent submission after time expired (race condition guard)
        if (roundTimeLeft <= 0) return;

        const timeSpent = settings.timePerRound - roundTimeLeft;

        set({ hasGuessed: true });

        // Broadcast guess to all
        broadcastEvent(channelRef, "SUBMIT_GUESS", {
            playerId: myId,
            position: guessPosition,
            timeSpent,
        });
    },

    /* ── Return to Lobby (Play Again) ────────────────────── */
    returnToLobby: () => {
        // Only host can initiate return to lobby
        if (get().isHost && channelRef) {
            broadcastEvent(channelRef, "RETURN_TO_LOBBY", {});
        }
        // Non-host: handled via broadcast listener
        if (!get().isHost) return;

        doReturnToLobby();
    },

    /* ── Reset ────────────────────────────────────────────── */
    resetMultiplayer: () => {
        clearTimers();
        destroyChannel();
        channelRef = null;
        subscribedOnce = false;
        roundLocations = [];
        currentRoundGuesses.clear();
        set({
            myId: "",
            myName: "",
            phase: "menu",
            lobbyCode: "",
            players: [],
            settings: { ...DEFAULT_SETTINGS },
            isHost: false,
            currentRound: 0,
            totalRounds: 5,
            roundTimeLeft: 60,
            actualPosition: null,
            panoId: null,
            panoPosition: null,
            guessPosition: null,
            hasGuessed: false,
            isLoadingLocation: false,
            countdownValue: 3,
            roundResults: null,
            leaderboard: [],
            error: null,
        });
    },
}));

/* ── Shared return-to-lobby logic ─────────────────────────── */

function doReturnToLobby() {
    const store = useMultiplayerStore;
    clearTimers();
    roundLocations = [];
    currentRoundGuesses.clear();
    store.setState({
        phase: "lobby",
        currentRound: 0,
        roundTimeLeft: store.getState().settings.timePerRound,
        actualPosition: null,
        panoId: null,
        panoPosition: null,
        guessPosition: null,
        hasGuessed: false,
        isLoadingLocation: false,
        countdownValue: 3,
        roundResults: null,
        leaderboard: [],
        error: null,
        // Reset player scores and guess status
        players: store.getState().players.map((p) => ({ ...p, score: 0, hasGuessed: false })),
    });
}

/* ── Presence Listener Setup ──────────────────────────────── */

function setupPresenceListeners(
    channel: RealtimeChannel,
    get: () => MultiplayerState,
    set: (partial: Partial<MultiplayerState>) => void,
) {
    // Sync: rebuild full player list from presence state
    channel.on("presence", { event: "sync" }, () => {
        const state = channel.presenceState<PresencePayload>();
        const presentPlayers = presenceToPlayers(state);
        const current = get().players;
        const currentPhase = get().phase;

        // During gameplay, keep disconnected players in the list (marked disconnected)
        if (currentPhase === "guessing" || currentPhase === "round-results" || currentPhase === "countdown") {
            const merged = current.map((existing) => {
                const present = presentPlayers.find((p) => p.id === existing.id);
                if (present) {
                    return { ...present, score: existing.score, hasGuessed: existing.hasGuessed, connected: true };
                }
                // Player disconnected during game — keep them but mark disconnected
                return { ...existing, connected: false };
            });
            // Add any new players that joined mid-game (unlikely but safe)
            for (const p of presentPlayers) {
                if (!merged.find((m) => m.id === p.id)) {
                    merged.push(p);
                }
            }
            set({ players: merged });

            // Host: if a player disconnects mid-round, treat them as having "guessed"
            // so the round doesn't hang waiting for them
            if (get().isHost && currentPhase === "guessing") {
                const updatedPlayers = get().players;
                const allDoneOrDisconnected = updatedPlayers.every(
                    (p) => p.hasGuessed || !p.connected
                );
                if (allDoneOrDisconnected && updatedPlayers.some((p) => p.hasGuessed)) {
                    hostEndRound();
                }
            }

            // Detect host disconnect — promote next connected player
            const hostPresent = presentPlayers.some((p) => p.isHost);
            if (!hostPresent && !get().isHost) {
                // Host left — find first connected non-host player and promote them
                const me = get().myId;
                const connectedNonHost = presentPlayers
                    .filter((p) => !p.isHost)
                    .sort((a, b) => a.id.localeCompare(b.id));

                if (connectedNonHost.length > 0 && connectedNonHost[0].id === me) {
                    // I'm the new host
                    console.log("[Multiplayer] Host disconnected, I am now host");
                    set({ isHost: true });

                    // Re-track presence as host
                    const myPresence = presentPlayers.find((p) => p.id === me);
                    if (myPresence) {
                        trackPresence(channel, { ...myPresence, isHost: true });
                    }

                    // If we're mid-game and the round was stuck, end it
                    if (currentPhase === "guessing") {
                        // Give a short delay for state to settle, then check if round should end
                        setTimeout(() => {
                            const players = useMultiplayerStore.getState().players;
                            const allDone = players.every((p) => p.hasGuessed || !p.connected);
                            if (allDone) hostEndRound();
                        }, 2000);
                    }
                }
            }
        } else {
            // In lobby or menu phases, just rebuild from presence (preserve scores)
            const merged = presentPlayers.map((p) => {
                const existing = current.find((c) => c.id === p.id);
                return existing
                    ? { ...p, score: existing.score, hasGuessed: existing.hasGuessed }
                    : p;
            });
            set({ players: merged });
        }
    });
}

/* ── Broadcast Listener Setup ─────────────────────────────── */

function setupBroadcastListeners(channel: RealtimeChannel) {
    const store = useMultiplayerStore;

    // Settings update (from host)
    channel.on("broadcast", { event: "SETTINGS_UPDATE" }, ({ payload }) => {
        store.setState({ settings: payload as LobbySettings });
    });

    // Game starting — all clients (host + non-host) start countdown together
    channel.on("broadcast", { event: "GAME_STARTING" }, ({ payload }) => {
        const data = payload as GameStartingPayload;
        store.setState({
            totalRounds: data.totalRounds,
            settings: data.settings,
        });

        // All clients start countdown (host locations already generated before broadcast)
        startCountdown(() => {
            // Only host starts round 1 when countdown finishes
            if (store.getState().isHost) {
                hostStartRound(1);
            }
            // Non-host: countdown ends, waits for ROUND_START broadcast from host
        });
    });

    // Round start
    channel.on("broadcast", { event: "ROUND_START" }, ({ payload }) => {
        const data = payload as RoundStartPayload;
        roundStartTime = Date.now();
        store.setState({
            phase: "guessing",
            currentRound: data.roundNum,
            roundTimeLeft: data.timeLimit,
            panoId: data.panoId,
            panoPosition: data.panoPosition,
            actualPosition: null, // Don't reveal until round ends
            guessPosition: null,
            hasGuessed: false,
            roundResults: null,
            isLoadingLocation: false,
            // Reset player hasGuessed status
            players: store.getState().players.map((p) => ({ ...p, hasGuessed: false })),
        });
    });

    // Player guessed
    channel.on("broadcast", { event: "PLAYER_GUESSED" }, ({ payload }) => {
        const data = payload as PlayerGuessedPayload;
        store.setState({
            players: store.getState().players.map((p) =>
                p.id === data.playerId ? { ...p, hasGuessed: true } : p
            ),
        });
    });

    // Submit guess (host collects)
    channel.on("broadcast", { event: "SUBMIT_GUESS" }, ({ payload }) => {
        const { isHost, players } = store.getState();
        const data = payload as { playerId: string; position: Position; timeSpent: number };

        // All clients update the "guessed" status
        store.setState({
            players: players.map((p) =>
                p.id === data.playerId ? { ...p, hasGuessed: true } : p
            ),
        });

        // Host collects all guesses
        if (isHost) {
            // Prevent duplicate guesses from same player
            if (currentRoundGuesses.has(data.playerId)) return;

            currentRoundGuesses.set(data.playerId, {
                position: data.position,
                timeSpent: data.timeSpent,
            });

            // Broadcast that this player has guessed
            broadcastEvent(channel, "PLAYER_GUESSED", { playerId: data.playerId });

            // Check if all connected players have guessed
            const updatedPlayers = store.getState().players;
            const allDone = updatedPlayers.every(
                (p) => p.hasGuessed || !p.connected
            );
            if (allDone) {
                hostEndRound();
            }
        }
    });

    // Timer update
    channel.on("broadcast", { event: "TIMER_UPDATE" }, ({ payload }) => {
        const data = payload as TimerUpdatePayload;
        store.setState({ roundTimeLeft: data.timeLeft });
    });

    // Round results
    channel.on("broadcast", { event: "ROUND_RESULTS" }, ({ payload }) => {
        const data = payload as RoundResultsPayload;
        clearTimers();

        // Update player scores
        const updatedPlayers = store.getState().players.map((p) => {
            const entry = data.leaderboard.find((e) => e.playerId === p.id);
            return entry ? { ...p, score: entry.totalScore } : p;
        });

        store.setState({
            phase: "round-results",
            roundResults: data,
            actualPosition: data.actualPosition,
            leaderboard: data.leaderboard,
            players: updatedPlayers,
        });

        // Auto-advance after 12 seconds (host broadcasts next round)
        if (store.getState().isHost) {
            autoAdvanceTimeout = setTimeout(() => {
                const { currentRound, totalRounds } = store.getState();
                if (currentRound < totalRounds) {
                    startCountdown(() => {
                        hostStartRound(currentRound + 1);
                    });
                } else {
                    hostEndMatch();
                }
            }, 12000);
        }
    });

    // Match over
    channel.on("broadcast", { event: "MATCH_OVER" }, ({ payload }) => {
        const data = payload as MatchOverPayload;
        clearTimers();
        store.setState({
            phase: "match-summary",
            leaderboard: data.leaderboard,
        });
    });

    // Return to lobby (from host, received by all clients)
    channel.on("broadcast", { event: "RETURN_TO_LOBBY" }, () => {
        doReturnToLobby();
    });
}

/* ── Host Round Management ────────────────────────────────── */

function hostStartRound(roundNum: number) {
    if (!channelRef) return;
    const store = useMultiplayerStore;
    const { settings } = store.getState();

    // Get pre-generated location
    const location = roundLocations[roundNum - 1];
    if (!location) return;

    currentRoundGuesses.clear();
    roundEnding = false; // Reset guard for the new round

    // Broadcast round start
    broadcastEvent(channelRef, "ROUND_START", {
        roundNum,
        timeLimit: settings.timePerRound,
        panoId: location.panoId,
        panoPosition: location.position,
    } as RoundStartPayload);

    // Start round timer
    let timeLeft = settings.timePerRound;
    timerInterval = setInterval(() => {
        timeLeft--;
        if (channelRef) {
            broadcastEvent(channelRef, "TIMER_UPDATE", { timeLeft } as TimerUpdatePayload);
        }
        // Also update host's own store directly (don't rely on broadcast round-trip)
        store.setState({ roundTimeLeft: timeLeft });
        if (timeLeft <= 0) {
            hostEndRound();
        }
    }, 1000);
}

function hostEndRound() {
    // Guard: prevent double invocation from timer + all-guessed race
    if (roundEnding) return;
    roundEnding = true;

    clearTimers();
    if (!channelRef) return;

    const store = useMultiplayerStore;
    const { currentRound, players } = store.getState();
    const location = roundLocations[currentRound - 1];
    if (!location) return;

    // Calculate results
    const results = computeRoundResults(
        currentRound,
        location.position,
        currentRoundGuesses,
        players
    );

    // Broadcast results
    broadcastEvent(channelRef, "ROUND_RESULTS", results);
}

function hostEndMatch() {
    if (!channelRef) return;
    const store = useMultiplayerStore;
    const { players } = store.getState();

    const finalResults = computeFinalLeaderboard(players);
    broadcastEvent(channelRef, "MATCH_OVER", finalResults);
}

/* ── Countdown ────────────────────────────────────────────── */

function startCountdown(onComplete: () => void) {
    const store = useMultiplayerStore;
    clearTimers(); // Clear any running countdown before starting a new one
    store.setState({ phase: "countdown", countdownValue: 3 });

    let count = 3;
    countdownInterval = setInterval(() => {
        count--;
        if (count > 0) {
            store.setState({ countdownValue: count });
        } else {
            clearInterval(countdownInterval!);
            countdownInterval = null;
            store.setState({ countdownValue: 0 });
            onComplete();
        }
    }, 1000);
}
