/**
 * Multiplayer Zustand Store
 * Manages all state for the LAN multiplayer mode.
 * Subscribes to Supabase Realtime channel events and drives the UI.
 */

import { create } from "zustand";
import type { RealtimeChannel } from "@supabase/supabase-js";
import type { Position } from "@/types/game";
import type {
    MultiplayerPhase,
    LobbySettings,
    LobbyPlayer,
    LeaderboardEntry,
    RoundStartPayload,
    RoundResultsPayload,
    MatchOverPayload,
    GameStartingPayload,
    PlayerGuessedPayload,
    TimerUpdatePayload,
} from "@/types/multiplayer";
import { AVATAR_COLORS } from "@/types/multiplayer";
import {
    generatePartyCode,
    getPlayerId,
    createChannel,
    destroyChannel,
    createGuessesChannel,
    destroyGuessesChannel,
    trackPresence,
    presenceToPlayers,
    broadcastEvent,
    computeRoundResults,
    computeFinalLeaderboard,
    waitForOtherPresence,
    readLobbyBreadcrumb,
    writeLobbyBreadcrumb,
    clearLobbyBreadcrumb,
} from "@/lib/multiplayer";
import type { PresencePayload } from "@/lib/multiplayer";
import { loadGoogleMaps } from "@/lib/google-maps";
import { findRandomStreetViewLocation, findStreetViewAt } from "@/lib/geo";

/* ── Store Interface ──────────────────────────────────────── */

interface MultiplayerState {
    // Identity
    myId: string;
    myName: string;

    // Lobby
    phase: MultiplayerPhase;
    lobbyCode: string;
    players: LobbyPlayer[];
    settings: LobbySettings;
    isHost: boolean;

    // Gameplay
    currentRound: number;
    totalRounds: number;
    roundTimeLeft: number;
    /** Revealed only when the round ends — never sent before then. */
    actualPosition: Position | null;
    panoId: string | null;
    guessPosition: Position | null;
    hasGuessed: boolean;
    isLoadingLocation: boolean;
    /** How many round locations the host has resolved so far (start progress). */
    locationsLoaded: number;

    // Countdown
    countdownValue: number;

    // Results
    roundResults: RoundResultsPayload | null;
    leaderboard: LeaderboardEntry[];

    // Error
    error: string | null;

    // Actions
    setMyName: (name: string) => void;
    createLobby: () => void;
    joinLobby: (code: string) => void;
    /** Re-enter the lobby recorded before a page refresh. True if one was found. */
    rejoinLobby: () => boolean;
    leaveLobby: () => void;
    updateSettings: (settings: Partial<LobbySettings>) => void;
    startGame: () => void;
    setGuessPosition: (pos: Position) => void;
    submitGuess: () => void;
    returnToLobby: () => void;
    resetMultiplayer: () => void;
}

/* ── Internal refs (not in Zustand to avoid serialization) ── */

let channelRef: RealtimeChannel | null = null;
/** Host-only-subscribed channel that carries raw guess positions (see setupGuessesListener). */
let guessesChannelRef: RealtimeChannel | null = null;
/**
 * The channel setupGuessesListener is currently attached to. Compared by identity
 * rather than a boolean so a listener is never suppressed on a *different* channel.
 */
let guessesListenerChannel: RealtimeChannel | null = null;
let timerInterval: ReturnType<typeof setInterval> | null = null;
let countdownInterval: ReturnType<typeof setInterval> | null = null;
let autoAdvanceTimeout: ReturnType<typeof setTimeout> | null = null;
let connectionTimeout: ReturnType<typeof setTimeout> | null = null;
/** Debounce for host promotion so presence has time to settle across clients. */
let promotionTimeout: ReturnType<typeof setTimeout> | null = null;

/** Locations pre-generated by host for all rounds. panoId is always non-empty. */
let roundLocations: { position: Position; panoId: string }[] = [];

/** Guesses received during current round (host only) */
let currentRoundGuesses: Map<string, { position: Position; timeSpent: number }> = new Map();

/** Guard to prevent hostEndRound from being called twice (timer + all-guessed race) */
let roundEnding = false;

/** Guard to prevent subscribe "SUBSCRIBED" callback from firing on reconnect */
let subscribedOnce = false;

function clearTimers() {
    if (timerInterval) { clearInterval(timerInterval); timerInterval = null; }
    if (countdownInterval) { clearInterval(countdownInterval); countdownInterval = null; }
    if (autoAdvanceTimeout) { clearTimeout(autoAdvanceTimeout); autoAdvanceTimeout = null; }
    if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
    if (promotionTimeout) { clearTimeout(promotionTimeout); promotionTimeout = null; }
}

/* ── Default Settings ─────────────────────────────────────── */

const DEFAULT_SETTINGS: LobbySettings = {
    rounds: 5,
    timePerRound: 60,
    mapType: "world",
};

/** Connection timeout duration in ms */
const CONNECTION_TIMEOUT_MS = 15_000;

/** Overall cap on pre-generating every round's location. */
const LOCATION_GEN_TIMEOUT_MS = 45_000;

/** How long to wait for presence to settle before promoting ourselves to host. */
const PROMOTION_DEBOUNCE_MS = 1_500;

/* ── Host: round location generation ──────────────────────── */

/**
 * Pre-generate one Street View location per round, in parallel.
 *
 * Every entry is guaranteed a non-empty panoId: ROUND_START ships only the
 * panorama id (the coordinates are the answer), so a location without one
 * would leave clients with nothing to render.
 */
async function generateRoundLocations(
    settings: LobbySettings,
    set: (partial: Partial<MultiplayerState>) => void,
): Promise<{ position: Position; panoId: string }[]> {
    let done = 0;

    const work = Promise.all(
        Array.from({ length: settings.rounds }, async () => {
            const loc = await findRandomStreetViewLocation(settings.mapType || "world", 12);
            let position: Position = { lat: loc.lat, lng: loc.lng };
            let panoId = "panoId" in loc ? (loc.panoId as string) || "" : "";

            if (!panoId) {
                // The curated-fallback branch returns bare coords — snap to a real pano.
                const snapped = await findStreetViewAt(position, 50_000);
                if (!snapped?.panoId) {
                    throw new Error("Could not resolve a Street View panorama.");
                }
                position = { lat: snapped.lat, lng: snapped.lng };
                panoId = snapped.panoId;
            }

            set({ locationsLoaded: ++done });
            return { position, panoId };
        }),
    );

    return Promise.race([
        work,
        new Promise<never>((_, reject) =>
            setTimeout(
                () => reject(new Error("Timed out finding locations. Please try again.")),
                LOCATION_GEN_TIMEOUT_MS,
            ),
        ),
    ]);
}

/* ── Store ────────────────────────────────────────────────── */

export const useMultiplayerStore = create<MultiplayerState>()((set, get) => ({
    myId: "",
    myName: "",
    phase: "menu",
    lobbyCode: "",
    players: [],
    settings: { ...DEFAULT_SETTINGS },
    isHost: false,
    currentRound: 0,
    totalRounds: 5,
    roundTimeLeft: 60,
    actualPosition: null,
    panoId: null,
    guessPosition: null,
    hasGuessed: false,
    isLoadingLocation: false,
    locationsLoaded: 0,
    countdownValue: 3,
    roundResults: null,
    leaderboard: [],
    error: null,

    setMyName: (name) => set({ myName: name }),

    /* ── Create Lobby ─────────────────────────────────────── */
    createLobby: () => {
        const { myName } = get();
        const code = generatePartyCode();
        const avatarColor = AVATAR_COLORS[0];

        try {
            // getPlayerId can throw when site data is blocked — keep it inside
            // the try so we surface an error instead of wedging on "creating".
            const myId = getPlayerId();

            set({
                phase: "creating",
                myId,
                lobbyCode: code,
                isHost: true,
                error: null,
            });

            const channel = createChannel(code);
            channelRef = channel;
            subscribedOnce = false;

            // Set up presence + broadcast listeners
            setupPresenceListeners(channel, get, set);
            setupBroadcastListeners(channel);

            // Host-only channel for raw guess positions — subscribe now since we're the host.
            const guessesChannel = createGuessesChannel(code);
            guessesChannelRef = guessesChannel;
            setupGuessesListener(guessesChannel);
            guessesChannel.subscribe();

            // Connection timeout — if we don't connect in 15s, abort
            connectionTimeout = setTimeout(() => {
                const currentPhase = get().phase;
                if (currentPhase === "creating") {
                    console.error("[Multiplayer] Connection timeout while creating lobby");
                    destroyChannel();
                    channelRef = null;
                    set({ phase: "menu", error: "Connection timed out. Please try again." });
                }
            }, CONNECTION_TIMEOUT_MS);

            // Subscribe and track presence
            channel.subscribe(async (status) => {
                console.log("[Multiplayer] Channel subscribe status:", status);
                if (status === "SUBSCRIBED") {
                    // Guard: only transition phase on first subscribe (not reconnects)
                    if (subscribedOnce) {
                        // Re-track presence on reconnect to restore our presence
                        await trackPresence(channel, {
                            id: myId,
                            name: myName || "Host",
                            avatarColor,
                            isHost: get().isHost,
                        });
                        return;
                    }
                    subscribedOnce = true;

                    if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }

                    const result = await trackPresence(channel, {
                        id: myId,
                        name: myName || "Host",
                        avatarColor,
                        isHost: true,
                    });

                    if (result === "error" || result === "timed out") {
                        console.error("[Multiplayer] Failed to track presence:", result);
                        set({ phase: "menu", error: "Failed to join channel. Please try again." });
                        return;
                    }

                    // Breadcrumb so a refresh can rejoin instead of dropping the lobby.
                    writeLobbyBreadcrumb(code, myName || "Host");
                    set({ phase: "lobby" });
                } else if (status === "CHANNEL_ERROR") {
                    console.error("[Multiplayer] Channel error during lobby creation");
                    if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
                    set({ phase: "menu", error: "Failed to create lobby. Check your connection." });
                } else if (status === "TIMED_OUT") {
                    console.error("[Multiplayer] Channel subscription timed out");
                    if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
                    set({ phase: "menu", error: "Connection timed out. Check your internet connection." });
                } else if (status === "CLOSED") {
                    console.warn("[Multiplayer] Channel closed");
                    // Only reset if we're still in a creating/lobby phase (not mid-game)
                    const currentPhase = get().phase;
                    if (currentPhase === "creating" || currentPhase === "lobby") {
                        if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
                        set({ phase: "menu", error: "Connection closed. Please try again." });
                    }
                }
            });
        } catch (err) {
            console.error("[Multiplayer] Error creating lobby:", err);
            if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
            set({ phase: "menu", error: "Failed to create lobby. Check your Supabase configuration." });
        }
    },

    /* ── Join Lobby ───────────────────────────────────────── */
    joinLobby: (code) => {
        const { myName } = get();
        const avatarIndex = Math.floor(Math.random() * AVATAR_COLORS.length);
        const avatarColor = AVATAR_COLORS[avatarIndex];
        const normalizedCode = code.toUpperCase();

        try {
            // See createLobby — getPlayerId must not throw outside the try.
            const myId = getPlayerId();

            set({
                phase: "joining",
                myId,
                lobbyCode: normalizedCode,
                isHost: false,
                error: null,
            });

            const channel = createChannel(normalizedCode);
            channelRef = channel;
            subscribedOnce = false;

            setupPresenceListeners(channel, get, set);
            setupBroadcastListeners(channel);

            // Handle only, not subscribed — we're not host, so we only ever
            // httpSend() our own guess to it; we must never receive from it.
            guessesChannelRef = createGuessesChannel(normalizedCode);

            // Connection timeout — if we don't connect in 15s, abort
            connectionTimeout = setTimeout(() => {
                const currentPhase = get().phase;
                if (currentPhase === "joining") {
                    console.error("[Multiplayer] Connection timeout while joining lobby");
                    destroyChannel();
                    channelRef = null;
                    set({ phase: "menu", error: "Connection timed out. Check the party code and try again." });
                }
            }, CONNECTION_TIMEOUT_MS);

            channel.subscribe(async (status) => {
                console.log("[Multiplayer] Join channel status:", status);
                if (status === "SUBSCRIBED") {
                    // Guard: only transition phase on first subscribe
                    if (subscribedOnce) {
                        await trackPresence(channel, {
                            id: myId,
                            name: myName || "Player",
                            avatarColor,
                            isHost: get().isHost,
                        });
                        return;
                    }
                    subscribedOnce = true;

                    if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }

                    const result = await trackPresence(channel, {
                        id: myId,
                        name: myName || "Player",
                        avatarColor,
                        isHost: false,
                    });

                    if (result === "error" || result === "timed out") {
                        console.error("[Multiplayer] Failed to track presence:", result);
                        set({ phase: "menu", error: "Failed to join lobby. Please try again." });
                        return;
                    }

                    // Realtime channels are created on demand, so a typo'd code
                    // "joins" successfully into an empty room. Require at least one
                    // other occupant before we call this a lobby.
                    const others = await waitForOtherPresence(channel, myId);
                    if (others.length === 0) {
                        console.warn("[Multiplayer] No players found in lobby", normalizedCode);
                        destroyChannel();
                        destroyGuessesChannel();
                        channelRef = null;
                        guessesChannelRef = null;
                        guessesListenerChannel = null;
                        clearLobbyBreadcrumb();
                        set({
                            phase: "menu",
                            error: `No lobby found with code ${normalizedCode}.`,
                        });
                        return;
                    }

                    writeLobbyBreadcrumb(normalizedCode, myName || "Player");
                    set({ phase: "lobby" });
                } else if (status === "CHANNEL_ERROR") {
                    console.error("[Multiplayer] Channel error during join");
                    if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
                    set({ phase: "menu", error: "Failed to join lobby. Check the party code." });
                } else if (status === "TIMED_OUT") {
                    console.error("[Multiplayer] Join channel timed out");
                    if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
                    set({ phase: "menu", error: "Connection timed out. Check your internet connection." });
                } else if (status === "CLOSED") {
                    console.warn("[Multiplayer] Join channel closed");
                    const currentPhase = get().phase;
                    if (currentPhase === "joining" || currentPhase === "lobby") {
                        if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
                        set({ phase: "menu", error: "Connection closed. Please try again." });
                    }
                }
            });
        } catch (err) {
            console.error("[Multiplayer] Error joining lobby:", err);
            if (connectionTimeout) { clearTimeout(connectionTimeout); connectionTimeout = null; }
            set({ phase: "menu", error: "Failed to join lobby. Check the party code and your connection." });
        }
    },

    /* ── Rejoin after a refresh ───────────────────────────── */
    rejoinLobby: () => {
        const crumb = readLobbyBreadcrumb();
        if (!crumb) return false;

        // Always rejoin as a plain player — if the original host was the one who
        // refreshed, presence-based promotion hands authority back (see
        // setupPresenceListeners). getPlayerId survives the refresh via
        // sessionStorage, so our old presence entry is replaced, not duplicated.
        console.log("[Multiplayer] Rejoining lobby after refresh:", crumb.code);
        useMultiplayerStore.getState().setMyName(crumb.name);
        useMultiplayerStore.getState().joinLobby(crumb.code);
        return true;
    },

    /* ── Leave Lobby ──────────────────────────────────────── */
    leaveLobby: () => {
        clearTimers();
        destroyChannel();
        destroyGuessesChannel();
        channelRef = null;
        guessesChannelRef = null;
        guessesListenerChannel = null;
        subscribedOnce = false;
        roundLocations = [];
        currentRoundGuesses.clear();
        clearLobbyBreadcrumb();
        set({
            phase: "menu",
            lobbyCode: "",
            players: [],
            isHost: false,
            currentRound: 0,
            roundResults: null,
            leaderboard: [],
            guessPosition: null,
            hasGuessed: false,
            actualPosition: null,
            panoId: null,
            isLoadingLocation: false,
            locationsLoaded: 0,
            error: null,
        });
    },

    /* ── Update Settings (Host only) ──────────────────────── */
    updateSettings: (partial) => {
        const newSettings = { ...get().settings, ...partial };
        set({ settings: newSettings });

        // Broadcast settings update to all players
        if (channelRef && get().isHost) {
            broadcastEvent(channelRef, "SETTINGS_UPDATE", newSettings);
        }
    },

    /* ── Start Game (Host only) ───────────────────────────── */
    startGame: async () => {
        const { isHost, settings, players, isLoadingLocation } = get();

        // Every exit path below must leave a visible state — a silent return
        // strands the lobby's Start button on its loading label forever.
        if (isLoadingLocation) return; // already starting
        if (!isHost) {
            set({ error: "Only the host can start the game." });
            return;
        }
        if (!channelRef) {
            set({ error: "Lost connection to the lobby. Please rejoin." });
            return;
        }
        if (players.length < 2) {
            set({ error: "Need at least 2 players to start." });
            return;
        }

        set({
            error: null,
            totalRounds: settings.rounds,
            isLoadingLocation: true,
            locationsLoaded: 0,
        });

        // Pre-generate all round locations FIRST, then broadcast + countdown
        try {
            await loadGoogleMaps();
            roundLocations = await generateRoundLocations(settings, set);

            set({ isLoadingLocation: false });

            // Locations ready — broadcast GAME_STARTING so all clients start countdown together
            broadcastEvent(channelRef, "GAME_STARTING", {
                totalRounds: settings.rounds,
                settings,
            } as GameStartingPayload);

            // Countdown is started from the GAME_STARTING broadcast listener
            // (host receives it too since self: true)
        } catch (err) {
            console.error("[Multiplayer] Failed to start game:", err);
            roundLocations = [];
            set({
                error:
                    err instanceof Error
                        ? err.message
                        : "Failed to generate locations. Please try again.",
                isLoadingLocation: false,
            });
        }
    },

    /* ── Guess ────────────────────────────────────────────── */
    setGuessPosition: (pos) => {
        if (!get().hasGuessed) {
            set({ guessPosition: pos });
        }
    },

    submitGuess: () => {
        const { guessPosition, hasGuessed, myId, settings, roundTimeLeft } = get();
        if (!guessPosition || hasGuessed || !channelRef) return;
        // Prevent submission after time expired (race condition guard)
        if (roundTimeLeft <= 0) return;

        const timeSpent = settings.timePerRound - roundTimeLeft;

        // Must be set before recordGuess below — that call can synchronously
        // end the round, which re-reads this flag.
        set({ hasGuessed: true });

        // Public: tell every client this player has guessed — no position,
        // just the flag that drives the "has guessed" checkmark in the UI.
        broadcastEvent(channelRef, "GUESS_SUBMITTED", { playerId: myId });

        if (get().isHost) {
            // We are the authority. httpSend is a REST round-trip, and a guess
            // still in flight when the timer expires would be scored as a miss —
            // so record our own guess directly instead.
            recordGuess(myId, guessPosition, timeSpent);
            return;
        }

        // Private: send the actual guess only to the host, via a channel
        // only the host is subscribed to (see setupGuessesListener). Works
        // whether or not this client is subscribed to that channel.
        if (guessesChannelRef) {
            guessesChannelRef
                .httpSend("SUBMIT_GUESS", { playerId: myId, position: guessPosition, timeSpent })
                .catch((err) => console.error("[Multiplayer] Failed to submit guess:", err));
        }
    },

    /* ── Return to Lobby (Play Again) ────────────────────── */
    returnToLobby: () => {
        // Only host can initiate return to lobby
        if (get().isHost && channelRef) {
            broadcastEvent(channelRef, "RETURN_TO_LOBBY", {});
        }
        // Non-host: handled via broadcast listener
        if (!get().isHost) return;

        doReturnToLobby();
    },

    /* ── Reset ────────────────────────────────────────────── */
    resetMultiplayer: () => {
        clearTimers();
        destroyChannel();
        destroyGuessesChannel();
        channelRef = null;
        guessesChannelRef = null;
        guessesListenerChannel = null;
        subscribedOnce = false;
        roundLocations = [];
        currentRoundGuesses.clear();
        clearLobbyBreadcrumb();
        set({
            myId: "",
            myName: "",
            phase: "menu",
            lobbyCode: "",
            players: [],
            settings: { ...DEFAULT_SETTINGS },
            isHost: false,
            currentRound: 0,
            totalRounds: 5,
            roundTimeLeft: 60,
            actualPosition: null,
            panoId: null,
            guessPosition: null,
            hasGuessed: false,
            isLoadingLocation: false,
            locationsLoaded: 0,
            countdownValue: 3,
            roundResults: null,
            leaderboard: [],
            error: null,
        });
    },
}));

/* ── Shared return-to-lobby logic ─────────────────────────── */

function doReturnToLobby() {
    const store = useMultiplayerStore;
    clearTimers();
    roundLocations = [];
    currentRoundGuesses.clear();
    store.setState({
        phase: "lobby",
        currentRound: 0,
        roundTimeLeft: store.getState().settings.timePerRound,
        actualPosition: null,
        panoId: null,
        guessPosition: null,
        hasGuessed: false,
        isLoadingLocation: false,
        locationsLoaded: 0,
        countdownValue: 3,
        roundResults: null,
        leaderboard: [],
        error: null,
        // Reset player scores and guess status
        players: store.getState().players.map((p) => ({ ...p, score: 0, hasGuessed: false })),
    });
}

/* ── Presence Listener Setup ──────────────────────────────── */

function setupPresenceListeners(
    channel: RealtimeChannel,
    get: () => MultiplayerState,
    set: (partial: Partial<MultiplayerState>) => void,
) {
    // Sync: rebuild full player list from presence state
    channel.on("presence", { event: "sync" }, () => {
        const state = channel.presenceState<PresencePayload>();
        const presentPlayers = presenceToPlayers(state);
        const current = get().players;
        const currentPhase = get().phase;

        // During gameplay, keep disconnected players in the list (marked disconnected)
        if (currentPhase === "guessing" || currentPhase === "round-results" || currentPhase === "countdown") {
            const merged = current.map((existing) => {
                const present = presentPlayers.find((p) => p.id === existing.id);
                if (present) {
                    return { ...present, score: existing.score, hasGuessed: existing.hasGuessed, connected: true };
                }
                // Player disconnected during game — keep them but mark disconnected
                return { ...existing, connected: false };
            });
            // Add any new players that joined mid-game (unlikely but safe)
            for (const p of presentPlayers) {
                if (!merged.find((m) => m.id === p.id)) {
                    merged.push(p);
                }
            }
            set({ players: merged });

            // Host: if a player disconnects mid-round, treat them as having "guessed"
            // so the round doesn't hang waiting for them
            if (get().isHost && currentPhase === "guessing") {
                const updatedPlayers = get().players;
                const allDoneOrDisconnected = updatedPlayers.every(
                    (p) => p.hasGuessed || !p.connected
                );
                if (allDoneOrDisconnected && updatedPlayers.some((p) => p.hasGuessed)) {
                    hostEndRound();
                }
            }

        } else {
            // In lobby or menu phases, just rebuild from presence (preserve scores)
            const merged = presentPlayers.map((p) => {
                const existing = current.find((c) => c.id === p.id);
                return existing
                    ? { ...p, score: existing.score, hasGuessed: existing.hasGuessed }
                    : p;
            });

            const patch: Partial<MultiplayerState> = { players: merged };
            // A start error ("need 2 players", "lost connection") is stale the
            // moment the roster changes. Scoped to the lobby so it can't swallow
            // connection errors raised while creating/joining.
            if (currentPhase === "lobby" && get().error) patch.error = null;
            set(patch);
        }

        // Host migration — runs in EVERY phase. A host leaving the lobby used to
        // strand everyone else on "waiting for host to start" forever.
        maybePromoteToHost(channel, presentPlayers, get, set);
    });
}

/**
 * If no host is present, the lowest-id player promotes itself. Debounced, because
 * every client evaluates this on the same sync event and one whose presence hasn't
 * propagated yet can briefly believe it is the lowest id.
 */
function maybePromoteToHost(
    channel: RealtimeChannel,
    presentPlayers: LobbyPlayer[],
    get: () => MultiplayerState,
    set: (partial: Partial<MultiplayerState>) => void,
) {
    if (get().isHost) return;
    if (presentPlayers.some((p) => p.isHost)) {
        // Host is back (or never left) — cancel any pending promotion.
        if (promotionTimeout) { clearTimeout(promotionTimeout); promotionTimeout = null; }
        return;
    }
    if (promotionTimeout) return; // already scheduled

    promotionTimeout = setTimeout(() => {
        promotionTimeout = null;

        const state = useMultiplayerStore.getState();
        if (state.isHost) return;

        // Re-check against live presence — the old host may have come back.
        const live = presenceToPlayers(channel.presenceState<PresencePayload>());
        if (live.length === 0 || live.some((p) => p.isHost)) return;

        const lowest = [...live].sort((a, b) => a.id.localeCompare(b.id))[0];
        if (lowest.id !== state.myId) return;

        console.log("[Multiplayer] No host present, I am now host");
        set({ isHost: true });

        const myPresence = live.find((p) => p.id === state.myId);
        if (myPresence) {
            trackPresence(channel, {
                id: myPresence.id,
                name: myPresence.name,
                avatarColor: myPresence.avatarColor,
                isHost: true,
            });
        }

        // We were send-only on the guesses channel before — subscribe now so we
        // actually receive future guesses.
        if (guessesChannelRef) {
            setupGuessesListener(guessesChannelRef);
            guessesChannelRef.subscribe();
        }

        // Round locations only ever existed in the previous host's tab — they are
        // never broadcast (that would leak the answers). Without them we cannot
        // drive the match, so end it cleanly instead of hanging forever.
        if (state.phase !== "lobby" && roundLocations.length === 0) {
            console.warn("[Multiplayer] Promoted without round data — ending match");
            if (channelRef) broadcastEvent(channelRef, "RETURN_TO_LOBBY", {});
            doReturnToLobby();
            set({ error: "The host left — the match was ended." });
        }
    }, PROMOTION_DEBOUNCE_MS);
}

/* ── Guesses Channel Listener (host only) ─────────────────── */

/**
 * Attaches the handler that collects raw guess positions on the host-only
 * guesses channel. Only ever meaningfully invoked by whoever is currently
 * host — non-host clients never subscribe to this channel, so they never
 * receive these events regardless of whether a listener is attached.
 */
/**
 * Host-side: record one player's guess into the authoritative map and end the
 * round once everyone connected has guessed. Called both from the guesses-channel
 * listener and directly by the host for its own guess (see submitGuess).
 */
function recordGuess(playerId: string, position: Position, timeSpent: number) {
    const store = useMultiplayerStore;
    if (!store.getState().isHost || !channelRef) return;

    // Prevent duplicate guesses from same player
    if (currentRoundGuesses.has(playerId)) return;

    currentRoundGuesses.set(playerId, { position, timeSpent });

    // Mark the player as guessed locally (don't wait on the round-trip of
    // the GUESS_SUBMITTED broadcast on the main channel to see our own update)
    store.setState({
        players: store.getState().players.map((p) =>
            p.id === playerId ? { ...p, hasGuessed: true } : p
        ),
    });

    // Confirm receipt to everyone (drives the "has guessed" checkmark)
    broadcastEvent(channelRef, "PLAYER_GUESSED", { playerId });

    // Check if all connected players have guessed
    const allDone = store.getState().players.every(
        (p) => p.hasGuessed || !p.connected
    );
    if (allDone) {
        hostEndRound();
    }
}

function setupGuessesListener(channel: RealtimeChannel) {
    if (guessesListenerChannel === channel) return;
    guessesListenerChannel = channel;

    channel.on("broadcast", { event: "SUBMIT_GUESS" }, ({ payload }) => {
        const data = payload as { playerId: string; position: Position; timeSpent: number };
        recordGuess(data.playerId, data.position, data.timeSpent);
    });
}

/* ── Broadcast Listener Setup ─────────────────────────────── */

function setupBroadcastListeners(channel: RealtimeChannel) {
    const store = useMultiplayerStore;

    // Settings update (from host)
    channel.on("broadcast", { event: "SETTINGS_UPDATE" }, ({ payload }) => {
        store.setState({ settings: payload as LobbySettings });
    });

    // Game starting — all clients (host + non-host) start countdown together
    channel.on("broadcast", { event: "GAME_STARTING" }, ({ payload }) => {
        const data = payload as GameStartingPayload;
        store.setState({
            totalRounds: data.totalRounds,
            settings: data.settings,
        });

        // All clients start countdown (host locations already generated before broadcast)
        startCountdown(() => {
            // Only host starts round 1 when countdown finishes
            if (store.getState().isHost) {
                hostStartRound(1);
            }
            // Non-host: countdown ends, waits for ROUND_START broadcast from host
        });
    });

    // Round start
    channel.on("broadcast", { event: "ROUND_START" }, ({ payload }) => {
        const data = payload as RoundStartPayload;
        store.setState({
            phase: "guessing",
            currentRound: data.roundNum,
            roundTimeLeft: data.timeLimit,
            panoId: data.panoId,
            actualPosition: null, // Don't reveal until round ends
            guessPosition: null,
            hasGuessed: false,
            roundResults: null,
            isLoadingLocation: false,
            // Reset player hasGuessed status
            players: store.getState().players.map((p) => ({ ...p, hasGuessed: false })),
        });
    });

    // Player guessed
    channel.on("broadcast", { event: "PLAYER_GUESSED" }, ({ payload }) => {
        const data = payload as PlayerGuessedPayload;
        store.setState({
            players: store.getState().players.map((p) =>
                p.id === data.playerId ? { ...p, hasGuessed: true } : p
            ),
        });
    });

    // Guess submitted (position-free — the actual position goes to the host
    // only, over the separate guesses-only channel; see setupGuessesListener).
    // Every client uses this just to flip the "has guessed" checkmark.
    channel.on("broadcast", { event: "GUESS_SUBMITTED" }, ({ payload }) => {
        const data = payload as { playerId: string };
        store.setState({
            players: store.getState().players.map((p) =>
                p.id === data.playerId ? { ...p, hasGuessed: true } : p
            ),
        });
    });

    // Timer update
    channel.on("broadcast", { event: "TIMER_UPDATE" }, ({ payload }) => {
        const data = payload as TimerUpdatePayload;
        store.setState({ roundTimeLeft: data.timeLeft });
    });

    // Round results
    channel.on("broadcast", { event: "ROUND_RESULTS" }, ({ payload }) => {
        const data = payload as RoundResultsPayload;
        clearTimers();

        // Update player scores
        const updatedPlayers = store.getState().players.map((p) => {
            const entry = data.leaderboard.find((e) => e.playerId === p.id);
            return entry ? { ...p, score: entry.totalScore } : p;
        });

        store.setState({
            phase: "round-results",
            roundResults: data,
            actualPosition: data.actualPosition,
            leaderboard: data.leaderboard,
            players: updatedPlayers,
        });

        // Auto-advance after 12 seconds (host broadcasts next round)
        if (store.getState().isHost) {
            autoAdvanceTimeout = setTimeout(() => {
                const { currentRound, totalRounds } = store.getState();
                if (currentRound < totalRounds) {
                    startCountdown(() => {
                        hostStartRound(currentRound + 1);
                    });
                } else {
                    hostEndMatch();
                }
            }, 12000);
        }
    });

    // Match over
    channel.on("broadcast", { event: "MATCH_OVER" }, ({ payload }) => {
        const data = payload as MatchOverPayload;
        clearTimers();
        store.setState({
            phase: "match-summary",
            leaderboard: data.leaderboard,
        });
    });

    // Return to lobby (from host, received by all clients)
    channel.on("broadcast", { event: "RETURN_TO_LOBBY" }, () => {
        doReturnToLobby();
    });
}

/* ── Host Round Management ────────────────────────────────── */

function hostStartRound(roundNum: number) {
    const store = useMultiplayerStore;
    const { settings } = store.getState();

    // Get pre-generated location
    const location = roundLocations[roundNum - 1];
    if (!channelRef || !location) {
        console.error("[Multiplayer] hostStartRound aborted — missing channel or location", { roundNum });
        if (channelRef) broadcastEvent(channelRef, "RETURN_TO_LOBBY", {});
        doReturnToLobby();
        store.setState({ error: "Round data missing — returned to the lobby." });
        return;
    }

    currentRoundGuesses.clear();
    roundEnding = false; // Reset guard for the new round

    // Broadcast round start. Only the panorama id goes out — the coordinates
    // ARE the answer, so they stay on the host until ROUND_RESULTS.
    broadcastEvent(channelRef, "ROUND_START", {
        roundNum,
        timeLimit: settings.timePerRound,
        panoId: location.panoId,
    } as RoundStartPayload);

    // Start round timer
    let timeLeft = settings.timePerRound;
    timerInterval = setInterval(() => {
        timeLeft--;
        if (channelRef) {
            broadcastEvent(channelRef, "TIMER_UPDATE", { timeLeft } as TimerUpdatePayload);
        }
        // Also update host's own store directly (don't rely on broadcast round-trip)
        store.setState({ roundTimeLeft: timeLeft });
        if (timeLeft <= 0) {
            hostEndRound();
        }
    }, 1000);
}

function hostEndRound() {
    // Guard: prevent double invocation from timer + all-guessed race
    if (roundEnding) return;

    const store = useMultiplayerStore;
    const { currentRound, players } = store.getState();
    const location = roundLocations[currentRound - 1];

    // Validate BEFORE latching the guard or killing the timer — otherwise an
    // abort here would block every future attempt to end this round.
    if (!channelRef || !location) {
        console.error("[Multiplayer] hostEndRound aborted — missing channel or location", { currentRound });
        return;
    }

    roundEnding = true;
    clearTimers();

    // Calculate results
    const results = computeRoundResults(
        currentRound,
        location.position,
        currentRoundGuesses,
        players
    );

    // Broadcast results
    broadcastEvent(channelRef, "ROUND_RESULTS", results);
}

function hostEndMatch() {
    if (!channelRef) return;
    const store = useMultiplayerStore;
    const { players } = store.getState();

    const finalResults = computeFinalLeaderboard(players);
    broadcastEvent(channelRef, "MATCH_OVER", finalResults);
}

/* ── Countdown ────────────────────────────────────────────── */

function startCountdown(onComplete: () => void) {
    const store = useMultiplayerStore;
    clearTimers(); // Clear any running countdown before starting a new one
    store.setState({ phase: "countdown", countdownValue: 3 });

    let count = 3;
    countdownInterval = setInterval(() => {
        count--;
        if (count > 0) {
            store.setState({ countdownValue: count });
        } else {
            clearInterval(countdownInterval!);
            countdownInterval = null;
            store.setState({ countdownValue: 0 });
            onComplete();
        }
    }, 1000);
}
